version: "3"
services:
  mongodb:
    image: mongo:5.0.2
    ports:
      - "27017:27017"
    volumes:
      - db:/data/db
  api:
    container_name: api
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "3010:3010"

volumes:
  db:
